### ISSUE TITLE
error during containers provisioning step (init.sh)

### ISSUE THREAD

**Issue by rafaeltuelho** [jbossdemocentral/bpms-fuse-travel-agency-integration-demo#8]
during init.sh execution it gets stuck in the following step, after creating the fabric containers:

```
...
Testing containers startd, retry when not ready, please be patient, it will take a while
...
```
around line `280`, there is a loop to test the conatiners' status
```
 #===Test if the fabric is ready=====================================
 echo Testing containers startd, retry when not ready, please be patient, it will take a while
 while true; do
     if [ $(sh $FUSE_SERVER_BIN/client 'container-list'| grep "success" | wc -l ) -ge 7 ]; then
         break
     fi
     sleep 2
 done
#===================================================================
```
But it seems there is a problem with the profiles assigned to the containers.

executing the `container-list` command inse the fuse fabric you can see dependency issues:
```
> ./client -u admin -p admin 'container-list'
Logging in as admin
403 [pool-2-thread-2] WARN org.apache.sshd.client.keyverifier.AcceptAllServerKeyVerifier - Server at [/0.0.0.0:8101, DSA, 8b:f1:7b:f7:56:fe:86:ff:5b:d7:92:84:a3:13:38:2f] presented unverified {} key: {}
[id]                           [version] [connected] [profiles]                                         [provision status]
root*                          1.0       true        fabric, fabric-ensemble-0000-1, jboss-fuse-full    success
  bookingflightcon             1.0       true        demo-travelagency-bookingservice                   error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requir
  bookinhotelgcon              1.0       true        demo-travelagency-hotelbookingservice              error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requir
  promoflightcon               1.0       true        demo-travelagency-promotionflight                  error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requir
  promohotelcon                1.0       true        demo-travelagency-promotionhotel                   error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requir
  wsflightcon                  1.0       true        demo-travelagency-webendpoint                      error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requir
  wshotelcon                   1.0       true        demo-travelagency-hotelwsendpoint                  error - org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requir

```

Looking inside the `demo-travelagency-bookingservice` container it is trying to lookup the `hibernate` feature. 

```
Provision Exception:
org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requirement [dummy/0.0.0] osgi.identity; osgi.identity=hibernate; type=karaf.feature; version=0
  at org.apache.felix.resolver.Candidates.populateResource(Candidates.java:285)
  at org.apache.felix.resolver.Candidates.populate(Candidates.java:153)
  at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:148)
  at io.fabric8.agent.DeploymentBuilder.resolve(DeploymentBuilder.java:231)
  at io.fabric8.agent.DeploymentAgent.doUpdate(DeploymentAgent.java:567)
  at io.fabric8.agent.DeploymentAgent$2.run(DeploymentAgent.java:293)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
```

But there is no `hibernate` feature installed in the fabric:

```
JBossFuse:admin@root> features:list | grep hibernate
[uninstalled] [4.5.0.redhat-611412    ] jpa-hibernate                           servicemix-4.5.0.redhat-611412
```
There is only `jpa-hibernate`.

the `fuseparent/hotelbookingservice/pom.xml` list the following features for the `demo-travelagency-hotelbookingservice` profile
```
<fabric8.features>camel-jpa activemq-camel hibernate jdbc</fabric8.features>
```
The same is true for `jdbc` feature. I think the correct one is `camel-jdbc`

**Comment by rafaeltuelho** [comment]
I tried to change the profile to use `jpa-hibernate` feature intead `hibernate` and `camel-jdbc` instead `jdbc`. But still not works.

It appears `jpa-hibernate` does not get installed in Fuse 6.1.1.

```
JBossFuse:admin@root> features:list | grep jpa-hibernate
[uninstalled] [4.5.0.redhat-611412    ] jpa-hibernate                           servicemix-4.5.0.redhat-611412
```

The profile can't find the `jpa-hibernate` feature:

```
Provision Exception:
org.osgi.service.resolver.ResolutionException: Unable to resolve dummy/0.0.0: missing requirement [dummy/0.0.0] osgi.identity; osgi.identity=jpa-hibernate; type=karaf.feature; version=0
  at org.apache.felix.resolver.Candidates.populateResource(Candidates.java:285)
  at org.apache.felix.resolver.Candidates.populate(Candidates.java:153)
  at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:148)
  at io.fabric8.agent.DeploymentBuilder.resolve(DeploymentBuilder.java:231)
  at io.fabric8.agent.DeploymentAgent.doUpdate(DeploymentAgent.java:567)
  at io.fabric8.agent.DeploymentAgent$2.run(DeploymentAgent.java:293)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
  at java.util.concurrent.FutureTask.run(FutureTask.java:262)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by weimeilin79** [comment]
Fixed the version. please check again!

**Comment by rafaeltuelho** [comment]
Hi @weimeilin79 

Still not working. There are two little issues.

 1. the version (`1.0.0.redhat-412`) of `fabric8-maven-plugin` specified in `fuseparent/pom.xml` does not work. See the mvn output:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.679 s
[INFO] Finished at: 2015-08-23T15:14:25-03:00
[INFO] Final Memory: 27M/331M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:1.0.0.redhat-412:deploy (default-cli) on project parent: Error executing: java.lang.IllegalArgumentException : Invalid version name 1.0.0.redhat-412 -> [Help 1]
```
I changed to version `1.2.0.Beta4` which was used in the release [`1.0`](https://github.com/jbossdemocentral/bpms-fuse-travel-agency-integration-demo/releases) of this demo and the build worked.

 2. In the relese 1.0 there was not Unit Tests. Now the projects have, but they are broken. The mvn tests are not working. See the mvn output:
```
...
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.494 sec <<< FAILURE!
testRoute(org.blogdemo.travelagency.RouteTest)  Time elapsed: 24.298 sec  <<< ERROR!
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[Message: 123]
        at org.apache.camel.util.ObjectHelper.wrapCamelExecutionException(ObjectHelper.java:1379)
        at org.apache.camel.util.ExchangeHelper.extractResultBody(ExchangeHelper.java:622)
        at org.apache.camel.impl.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:467)
        at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:133)
        at org.apache.camel.impl.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:149)
        at org.apache.camel.impl.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:297)
        at org.apache.camel.impl.DefaultProducerTemplate.requestBody(DefaultProducerTemplate.java:327)
        at org.blogdemo.travelagency.RouteTest.testRoute(RouteTest.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: org.apache.camel.ExchangeTimedOutException: The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-rsoares-47609-1440367182665-0-3 not received. Exchange[Message: 123]
        at org.apache.camel.component.jms.reply.ReplyManagerSupport.processReply(ReplyManagerSupport.java:133)
        at org.apache.camel.component.jms.reply.TemporaryQueueReplyHandler.onTimeout(TemporaryQueueReplyHandler.java:61)
        at org.apache.camel.component.jms.reply.CorrelationTimeoutMap.onEviction(CorrelationTimeoutMap.java:53)
        at org.apache.camel.component.jms.reply.CorrelationTimeoutMap.onEviction(CorrelationTimeoutMap.java:30)
        at org.apache.camel.support.DefaultTimeoutMap.purge(DefaultTimeoutMap.java:212)
        at org.apache.camel.support.DefaultTimeoutMap.run(DefaultTimeoutMap.java:162)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

[         ActiveMQ ShutdownHook] BrokerService                  INFO  Apache ActiveMQ 5.9.0.redhat-610379 (test-broker-1, ID:rsoares-37620-1440367182936-2:1) is shutting down
[         ActiveMQ ShutdownHook] TransportConnector             INFO  Connector vm://test-broker-1 stopped
[Executor: vm://test-broker-1#0] PooledConnectionFactory        INFO  Expiring connection ActiveMQConnection {id=ID:rsoares-37620-1440367182936-5:1,clientId=ID:rsoares-37620-1440367182936-4:1,started=false} on IOException: org.apache.activemq.transport.TransportDisposedIOException: peer (vm://test-broker-1#1) stopped.
[         ActiveMQ ShutdownHook] BrokerService                  INFO  Apache ActiveMQ 5.9.0.redhat-610379 (test-broker-1, ID:rsoares-37620-1440367182936-2:1) uptime 21.203 seconds
[         ActiveMQ ShutdownHook] BrokerService                  INFO  Apache ActiveMQ 5.9.0.redhat-610379 (test-broker-1, ID:rsoares-37620-1440367182936-2:1) is shutdown

Results :

Tests in error:
  testRoute(org.blogdemo.travelagency.RouteTest): Exception occurred during execution on the exchange: Exchange[Message: 123]

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.044 s
[INFO] Finished at: 2015-08-23T19:00:05-03:00
[INFO] Final Memory: 18M/310M
[INFO] ------------------------------------------------------------------------
...
```

One workaround for this 2nd issue is to pass the `-DskipTests` flag in the 
```
mvn fabric8:deploy -DskipTests
```

**Comment by eschabell** [comment]
All updated to fuse 6.2, please retest and reopen if needed.
